web:
  wordlists:
    directory: /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt
    subdomain: /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt
    vhost: /usr/share/seclists/Discovery/DNS/subdomains-top1million-20000.txt
  security_headers:
    mode_default: web
    profiles:
      web:
        enabled_headers:
          strict-transport-security: true
          content-security-policy: true
          x-frame-options: true
          x-content-type-options: true
          referrer-policy: true
          permissions-policy: true
          cross-origin-embedder-policy: false
          cross-origin-opener-policy: false
          cross-origin-resource-policy: false
          x-xss-protection: true
          cache-control: false
      api:
        enabled_headers:
          strict-transport-security: true
          content-security-policy: true
          x-frame-options: false
          x-content-type-options: true
          referrer-policy: false
          permissions-policy: false
          cross-origin-embedder-policy: false
          cross-origin-opener-policy: false
          cross-origin-resource-policy: false
          x-xss-protection: false
          cache-control: true
    info_disclosure_headers:
      server: true
      x-powered-by: true
      x-aspnet-version: true
      x-aspnetmvc-version: true
    scoring:
      enable_bonus_points: true
    output:
      format: table
  configs:
    protocol:
      default: "http"
      https: "https"

infra:
  configs:
    nmap:
      mode:
        default: ""
        udp: "-sU"
        stealth: "-sS -T2"
        full: "-sV -sC -A -p-"
        quick: "-sV -F"
    smbclient:
      auth:
        default: ""
        none: "-N"
        guest: "-N -U ''"
    msf:
      payload:
        default: "windows/meterpreter/reverse_tcp"
        linux_tcp: "linux/x64/meterpreter/reverse_tcp"
        linux_shell: "linux/x64/shell_reverse_tcp"
        windows_shell: "windows/x64/shell_reverse_tcp"
        windows_https: "windows/meterpreter/reverse_https"
    msfvenom:
      format:
        exe: "exe"
        elf: "elf"
        macho: "macho"
        raw: "raw"
        ps1: "ps1"
        war: "war"
        py: "py"
